network:
  name: "case300_ieee"
  source: "pglib"
  network_dir: "scripts/grids"

load:
  generator: "agg_load_profile"
  agg_profile: "default"
  scenarios: 3000
  sigma: 0.2
  change_reactive_power: true
  global_range: 0.4
  max_scaling_factor: 4.0
  step_size: 0.1
  start_scaling_factor: 1.0

topology_perturbation:
  type: "none" # "PowerGraph (PG)": load perturbation only, no topology changes

generation_perturbation:
  type: "cost_permutation"
  sigma: 1.0

admittance_perturbation:
  type: "none"

settings:
  num_processes: 32
  data_dir: "./data_out/repro"
  large_chunk_size: 1000
  overwrite: true
  mode: "pf"
  include_dc_res: true
  enable_solver_logs: false
  pf_fast: true
  dcpf_fast: true
  max_iter: 200
  seed: 42
